# Generated by Django 3.1.3 on 2020-11-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=8, verbose_name='Student ID')),
                ('address', models.CharField(max_length=1024, verbose_name='Address')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal Code')),
                ('tract_id', models.CharField(max_length=64, verbose_name='Tract ID')),
                ('neighborhood_rating', models.CharField(max_length=12, verbose_name='Neighborhood Rating')),
                ('kfr', models.CharField(max_length=12, verbose_name='KFR')),
            ],
        ),
    ]
