# Generated by Django 3.1.4 on 2020-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='akeb_rating',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='school',
            name='greatschools_rating',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='school',
            name='niche_rating',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='school',
            name='stanford_rating',
            field=models.CharField(max_length=8),
        ),
    ]
