# Generated by Django 3.1.3 on 2020-11-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='Texas', max_length=64, verbose_name='State'),
            preserve_default=False,
        ),
    ]
