# Generated by Django 3.1.4 on 2021-01-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oab', '0003_auto_20201227_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_id', models.FloatField(blank=True, default=-1, null=True)),
                ('neighborhood_quality', models.FloatField(blank=True, default=-1, null=True)),
            ],
        ),
    ]
